version: '3.8'

services:
  hono-psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - '5432:5432'
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
